# Run by the following block of code
if __name__ == '__main__':
  unittest.main()

# Results printed on the console
----------------------
Ran 1 test in 0.00s
OK

# The possible outcomes are
  # OK – all tests passed
  # FAIL – one or many tests failed and an AssertionError exception is raised
  # ERROR – the tests raised an exception other than AssertionError
